language: python

python:
  - "2.7"

branches:
  only:
    - feature/feature-3-data-ingestor

notifications:
  email:
    - srameshv@indiana.edu

sudo: true

install:
  - pip install -r core/python/DataIngestor/requirements.txt

script: cd "core/python/DataIngestor" && python DataIngestorTest.py

before_deploy:
  - cd..
  - zip -r TeamBash_DataIngestor.zip DataIngestor || true
  - mkdir -p "dpl_cd_upload1"
  - mv TeamBash_DataIngestor.zip dpl_cd_upload1/TeamBash_DataIngestor.zip || true
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: team-bash
    local_dir: dpl_cd_upload1
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: feature/feature-3-data-ingestor


